import Head from 'next/head'
import Link from 'next/link';
// import Image from 'next/image'
// import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-10 flex w-8/9 flex-row justify-between rounded-xl bg-highlight p-20">
        <div>
            {/* eslint-disable-next-line react/no-unescaped-entities */}
            <h1 className='text-4xl'>Cesar's Portfolio</h1>
            <h2 className="text-2xl">Welcome to my portfolio.</h2>
            <p className="pt-10">test</p>
          </div>
          <div className="relative w-500 m-10 font-serif">
          <Link href="/projects">My Favorite Projects:</Link>
          </div>
      </main>
    </>
  )
}
